# SAMPLE DATA

Tahapan ini merupakan tahapan membuat data sampel secara manual yang digunakan untuk menguji teknik data preprocessing 

In [5]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-1.5, 2.4, 3.5],
                        [5.9, 2.3, -5.8],
                        [0.5, -7.9, 5.6]
                       ])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 5.9,  2.3, -5.8],
       [ 0.5, -7.9,  5.6]])

In [6]:
sample_data.shape

(4, 3)

# TEKNIK DATA PREPROCESSING 1 : BINARISATION

Binarisation digunakan untuk merubah data numerik menjadi bilangan biner (1 atau 0) yang ditentukan melalui nilai parameter ambang batas yang ditentukan, contoh dibawah menggunakan nilai ambang batas 0.5

In [9]:
processor = preprocessing.Binarizer(threshold = 0.5)
binarised_data = processor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 0.],
       [0., 0., 1.]])

# TEKNIK DATA PREPROCESSING 2 : SCALING

In [11]:
preprocessor = preprocessing.MinMaxScaler(feature_range = (0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [1.        , 0.99029126, 0.        ],
       [0.27027027, 0.        , 1.        ]])

Apabila fit() dan transform() dikenakan pada satu objek maka dapat disederhanakan penulisannya sebagai berikut,

In [12]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [1.        , 0.99029126, 0.        ],
       [0.27027027, 0.        , 1.        ]])

# TEKNIK DATA PREPROCESSING 3 : NORMALIZATION

## L1 Nomalization : Least Absolute Deviation

In [13]:
l1_normalized_data = preprocessing.normalize(sample_data, 'l1')
l1_normalized_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.42142857,  0.16428571, -0.41428571],
       [ 0.03571429, -0.56428571,  0.4       ]])

## L1 Nomalization : Least Square

In [14]:
l2_normalized_data = preprocessing.normalize(sample_data, 'l2')
l2_normalized_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.68706914,  0.26784051, -0.6754239 ],
       [ 0.05156558, -0.81473612,  0.57753446]])